"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ThemeToggle } from "@/components/theme-toggle";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted/20">
      {/* Header */}
      <header className="border-b border-border/40 backdrop-blur-xl bg-background/80 sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <div className="flex items-center space-x-4">
            <Link href="/">
              <Button variant="ghost" size="icon" className="h-9 w-9">
                <ArrowLeft className="h-4 w-4" />
              </Button>
            </Link>
            <div className="flex items-center space-x-3">
              <Image
                src="/images/logo.png"
                alt="QR Engine Logo"
                width={32}
                height={32}
                className="rounded-lg"
              />
              <span className="font-semibold text-xl">QR Engine</span>
            </div>
          </div>
          <ThemeToggle />
        </div>
      </header>

      <main className="container mx-auto px-4 py-16 max-w-4xl">
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            Terms of Service
          </h1>
          <p className="text-xl text-muted-foreground">
            Simple terms for using QR Engine
          </p>
        </div>

        <div className="prose prose-neutral dark:prose-invert max-w-none">
          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-bold mb-4">Acceptance of Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                By downloading and using QR Engine, you agree to these terms. If
                you don&apos;t agree with these terms, please don&apos;t use the
                app.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">
                Description of Service
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                QR Engine is a mobile application for iOS that allows users to
                scan and generate QR codes. The app operates entirely offline
                and does not collect or transmit any personal data.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">User Responsibilities</h2>
              <ul className="space-y-2 text-muted-foreground">
                <li>• Use the app only for lawful purposes</li>
                <li>
                  • Do not scan QR codes that may contain malicious content
                </li>
                <li>
                  • Respect the privacy and rights of others when sharing QR
                  codes
                </li>
                <li>
                  • Use the camera feature responsibly and in accordance with
                  local laws
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">
                Limitations of Liability
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                QR Engine is provided &quot;as is&quot; without warranties. The
                developer is not responsible for any damages or issues arising
                from the use of QR codes generated or scanned with the app.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Privacy</h2>
              <p className="text-muted-foreground leading-relaxed">
                QR Engine respects your privacy completely. No data is
                collected, stored, or transmitted. Please refer to our{" "}
                <Link href="/privacy" className="text-blue-500 hover:underline">
                  Privacy Policy
                </Link>{" "}
                for detailed information.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Intellectual Property</h2>
              <p className="text-muted-foreground leading-relaxed">
                QR Engine and its design are the intellectual property of
                Ibrahim Uzun. QR codes generated by the app belong to the user
                who created them.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Changes to Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                These terms may be updated occasionally. Significant changes
                will be communicated through app updates or the App Store
                listing.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Contact Information</h2>
              <p className="text-muted-foreground leading-relaxed">
                For questions about these terms, contact Ibrahim Uzun through
                the App Store or social media.
              </p>
              <p className="text-sm text-muted-foreground mt-4">
                <strong>Developer:</strong> Ibrahim Uzun
                <br />
                <strong>Last Updated:</strong> August 2025
              </p>
            </section>
          </div>
        </div>

        {/* Back to Home */}
        <div className="text-center mt-16">
          <Link href="/">
            <Button size="lg" variant="outline">
              <ArrowLeft className="mr-2 w-4 h-4" />
              Back to Home
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}
